version: "3"

services:
  ownfoil:
    container_name: localfoil
    build:
      context: .
    restart: unless-stopped
    image: myownfoil:latest
    volumes:
      - /mnt/usb1/ownfoil/games:/games
      # Uncomment if you want to edit and persist the app configuration
      # - /mnt/usb1/ownfoil/app:/app
      # Uncomment to setup basic auth
      # - /mnt/usb1/ownfoil/nginx:/etc/nginx
    ports:
      - 8000:80
